# Generated by Django 4.2.1 on 2024-03-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_is_completed_tournament_is_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False, help_text='Indicates if the match is a bye.'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_bye',
            field=models.BooleanField(default=False, help_text='Indicates if the participant is a placeholder for a bye.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_participant_two', to='tournament.participant'),
        ),
    ]
