"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent / 'frontend'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# to be removed ==================================================================================
SECRET_KEY = 'django-insecure-6llr!9x37@9f)m=l-eshn0*65=1=1u#k)=*=6=_llj6p*xtqh1'
DEBUG = True
# ===================================================================================

#This allows access to your backend from these hosts/domains, but it doesn't directly affect CORS. CORS relies on different headers sent by the backend API.
ALLOWED_HOSTS = ['127.0.0.1','localhost']
#This allows cookies for CSRF protection from the specified origins.
CSRF_TRUSTED_ORIGINS = ['https://127.0.0.1:8080']
# This allows requests from both your frontend and your backend itself (useful for API calls within application).
CORS_ALLOWED_ORIGINS = ['https://127.0.0.1:8080', 'https://127.0.0.1:443', 'https://127.0.0.1:8000']
#This allows sending cookies across origins, necessary for authentication scenarios involving cookies.
CORS_ALLOW_CREDENTIALS = True
#This defines allowed HTTP methods for CORS requests.
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ORIGIN_ALLOW_ALL = True
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'tournament',
    'pongApp',
    'user_auth' 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #do not change the order 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'user_auth.middleware.JWTAuthenticationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_auth.middleware.UpdateLastActivityMiddleware']


ROOT_URLCONF = 'core.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Specify the correct database backend
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD':'postgres',
        'HOST': 'db',
        'PORT': 5432
    }
}

AUTH_USER_MODEL = 'user_auth.WebUser'
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
LOGIN_URL = '/login'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    FRONTEND_DIR / 'static',  # Adjust according to your actual static files directory
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Settings
JWT_SECRET_KEY = SECRET_KEY 
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_DELTA = timedelta(hours=1) 

# 42 OAuth settings
CLIENT_ID_42 = 'u-s4t2ud-d0c4077a43cbefbff3d67add430fbc7edaadbc4522099efc1eb7a28773e0037a'
CLIENT_SECRET_42 = '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'
CALLBACK_URL_42 = 'https://127.0.0.1:443/oauth_callback'

# SSL Settings
# below to ensure that all traffic is redirected to HTTPS
SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Email settings // has to be moved to .env file
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ft.transcendence.pong@gmail.com'
EMAIL_HOST_PASSWORD = 'aoqlnbmaqviznnmw'
EMAIL_USE_TLS = True
EMIAL_USE_SSL = False

#SEND_GRID_RECOVER_CODE  = FWHVDD5UD66EDBKHFQUX4CNS


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = '/code/media'


# curl -X POST https://api.intra.42.fr/oauth/token \
#      -d grant_type=client_credentials \
#      -d client_id=u-s4t2ud-d0c4077a43cbefbff3d67add430fbc7edaadbc4522099efc1eb7a28773e0037a\
#      -d client_secret=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


# curl -H "Authorization: Bearer a7661200d7f7133f943b7336f8086a02c712318ad88650343ff0bcaa11feec4d" \
#      https://api.intra.42.fr/v2/me

# get user by id 
# curl  -H "Authorization: Bearer a7661200d7f7133f943b7336f8086a02c712318ad88650343ff0bcaa11feec4d" "https://api.intra.42.fr/v2/users/101375"



# filter by id 
# curl  -H "Authorization: Bearer a7661200d7f7133f943b7336f8086a02c712318ad88650343ff0bcaa11feec4d" 'https://api.intra.42.fr/v2/users?filter\[login\]=aelsiddi'
# curl -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
#      "https://api.intra.42.fr/v2/users?filter[id]=101375"