services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - local_network
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app
      - shared_static_data:/frontend/static
      - ./ssl:/etc/nginx/ssl:ro
      - media_volume:/backend/media

  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - local_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - media_volume:/code/media
    ports:
      - "8081:8080"
      - "443:443"
    networks:
      - local_network
    environment:
      - BACKEND_URL=http://django:8000
    depends_on:
      - django
    restart: always

volumes:
  postgres_data:
  shared_static_data:
  media_volume:

networks:
  local_network:
    driver: bridge
