--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: otp_static_staticdevice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_static_staticdevice (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    confirmed boolean NOT NULL,
    user_id bigint NOT NULL,
    throttling_failure_count integer NOT NULL,
    throttling_failure_timestamp timestamp with time zone,
    CONSTRAINT otp_static_staticdevice_throttling_failure_count_check CHECK ((throttling_failure_count >= 0))
);


ALTER TABLE public.otp_static_staticdevice OWNER TO postgres;

--
-- Name: otp_static_staticdevice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_static_staticdevice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_static_staticdevice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_static_statictoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_static_statictoken (
    id integer NOT NULL,
    token character varying(16) NOT NULL,
    device_id integer NOT NULL
);


ALTER TABLE public.otp_static_statictoken OWNER TO postgres;

--
-- Name: otp_static_statictoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_static_statictoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_static_statictoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_totp_totpdevice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_totp_totpdevice (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    confirmed boolean NOT NULL,
    key character varying(80) NOT NULL,
    step smallint NOT NULL,
    t0 bigint NOT NULL,
    digits smallint NOT NULL,
    tolerance smallint NOT NULL,
    drift smallint NOT NULL,
    last_t bigint NOT NULL,
    user_id bigint NOT NULL,
    throttling_failure_count integer NOT NULL,
    throttling_failure_timestamp timestamp with time zone,
    CONSTRAINT otp_totp_totpdevice_digits_check CHECK ((digits >= 0)),
    CONSTRAINT otp_totp_totpdevice_step_check CHECK ((step >= 0)),
    CONSTRAINT otp_totp_totpdevice_throttling_failure_count_check CHECK ((throttling_failure_count >= 0)),
    CONSTRAINT otp_totp_totpdevice_tolerance_check CHECK ((tolerance >= 0))
);


ALTER TABLE public.otp_totp_totpdevice OWNER TO postgres;

--
-- Name: otp_totp_totpdevice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_totp_totpdevice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_totp_totpdevice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pong_match; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pong_match (
    id bigint NOT NULL,
    guest_player1 character varying(20),
    guest_player2 character varying(20),
    match_date timestamp with time zone NOT NULL,
    score_player integer NOT NULL,
    score_guest_player1 integer NOT NULL,
    score_guest_player2 integer,
    winner character varying(10),
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    player_id bigint NOT NULL
);


ALTER TABLE public.pong_match OWNER TO postgres;

--
-- Name: pong_match_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pong_match ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pong_match_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tournament_match; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tournament_match (
    id bigint NOT NULL,
    match_order integer NOT NULL,
    result character varying(255),
    is_completed boolean NOT NULL,
    round_number integer NOT NULL,
    loser_id bigint,
    participant_one_id bigint NOT NULL,
    participant_two_id bigint,
    tournament_id bigint NOT NULL,
    winner_id bigint,
    is_bye boolean NOT NULL
);


ALTER TABLE public.tournament_match OWNER TO postgres;

--
-- Name: tournament_match_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tournament_match ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tournament_match_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tournament_participant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tournament_participant (
    id bigint NOT NULL,
    temp_username character varying(255),
    tournament_id bigint NOT NULL,
    user_id bigint,
    is_bye boolean NOT NULL
);


ALTER TABLE public.tournament_participant OWNER TO postgres;

--
-- Name: tournament_participant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tournament_participant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tournament_participant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tournament_tournament; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tournament_tournament (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    creator_id bigint NOT NULL,
    is_completed boolean NOT NULL,
    is_started boolean NOT NULL,
    winner_id bigint
);


ALTER TABLE public.tournament_tournament OWNER TO postgres;

--
-- Name: tournament_tournament_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tournament_tournament ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tournament_tournament_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_custompermissionsmixin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_custompermissionsmixin (
    id bigint NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.user_auth_custompermissionsmixin OWNER TO postgres;

--
-- Name: user_auth_custompermissionsmixin_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_custompermissionsmixin_groups (
    id bigint NOT NULL,
    custompermissionsmixin_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_auth_custompermissionsmixin_groups OWNER TO postgres;

--
-- Name: user_auth_custompermissionsmixin_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_custompermissionsmixin_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_custompermissionsmixin_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_custompermissionsmixin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_custompermissionsmixin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_custompermissionsmixin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_custompermissionsmixin_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_custompermissionsmixin_user_permissions (
    id bigint NOT NULL,
    custompermissionsmixin_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_auth_custompermissionsmixin_user_permissions OWNER TO postgres;

--
-- Name: user_auth_custompermissionsmixin_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_custompermissionsmixin_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_custompermissionsmixin_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_userotp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_userotp (
    id bigint NOT NULL,
    otp character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_auth_userotp OWNER TO postgres;

--
-- Name: user_auth_userotp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_userotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_userotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_webuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_webuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(20) NOT NULL,
    email character varying(50) NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    phone_number character varying(17),
    address character varying(100) NOT NULL,
    profile_picture character varying(100),
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    "GDPR_agreement" boolean NOT NULL,
    "GDPR_agreement_date" timestamp with time zone,
    google_auth boolean NOT NULL,
    intra_auth boolean NOT NULL,
    github_auth boolean NOT NULL,
    twofa_enabled boolean NOT NULL,
    twofa_secret character varying(255),
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL
);


ALTER TABLE public.user_auth_webuser OWNER TO postgres;

--
-- Name: user_auth_webuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_webuser_groups (
    id bigint NOT NULL,
    webuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_auth_webuser_groups OWNER TO postgres;

--
-- Name: user_auth_webuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_webuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_webuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_webuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_webuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_webuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_webuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_auth_webuser_user_permissions (
    id bigint NOT NULL,
    webuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_auth_webuser_user_permissions OWNER TO postgres;

--
-- Name: user_auth_webuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_auth_webuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_webuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: otp_static_staticdevice otp_static_staticdevice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_static_staticdevice
    ADD CONSTRAINT otp_static_staticdevice_pkey PRIMARY KEY (id);


--
-- Name: otp_static_statictoken otp_static_statictoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_static_statictoken
    ADD CONSTRAINT otp_static_statictoken_pkey PRIMARY KEY (id);


--
-- Name: otp_totp_totpdevice otp_totp_totpdevice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_totp_totpdevice
    ADD CONSTRAINT otp_totp_totpdevice_pkey PRIMARY KEY (id);


--
-- Name: pong_match pong_match_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pong_match
    ADD CONSTRAINT pong_match_pkey PRIMARY KEY (id);


--
-- Name: tournament_match tournament_match_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_pkey PRIMARY KEY (id);


--
-- Name: tournament_participant tournament_participant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_participant
    ADD CONSTRAINT tournament_participant_pkey PRIMARY KEY (id);


--
-- Name: tournament_participant tournament_participant_tournament_id_user_id_te_b02b882d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_participant
    ADD CONSTRAINT tournament_participant_tournament_id_user_id_te_b02b882d_uniq UNIQUE (tournament_id, user_id, temp_username);


--
-- Name: tournament_tournament tournament_tournament_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_tournament
    ADD CONSTRAINT tournament_tournament_pkey PRIMARY KEY (id);


--
-- Name: user_auth_custompermissionsmixin_user_permissions user_auth_custompermissi_custompermissionsmixin_i_76c7d7ca_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_user_permissions
    ADD CONSTRAINT user_auth_custompermissi_custompermissionsmixin_i_76c7d7ca_uniq UNIQUE (custompermissionsmixin_id, permission_id);


--
-- Name: user_auth_custompermissionsmixin_groups user_auth_custompermissi_custompermissionsmixin_i_e01293ed_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_groups
    ADD CONSTRAINT user_auth_custompermissi_custompermissionsmixin_i_e01293ed_uniq UNIQUE (custompermissionsmixin_id, group_id);


--
-- Name: user_auth_custompermissionsmixin_groups user_auth_custompermissionsmixin_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_groups
    ADD CONSTRAINT user_auth_custompermissionsmixin_groups_pkey PRIMARY KEY (id);


--
-- Name: user_auth_custompermissionsmixin user_auth_custompermissionsmixin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin
    ADD CONSTRAINT user_auth_custompermissionsmixin_pkey PRIMARY KEY (id);


--
-- Name: user_auth_custompermissionsmixin_user_permissions user_auth_custompermissionsmixin_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_user_permissions
    ADD CONSTRAINT user_auth_custompermissionsmixin_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_auth_userotp user_auth_userotp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_userotp
    ADD CONSTRAINT user_auth_userotp_pkey PRIMARY KEY (id);


--
-- Name: user_auth_webuser user_auth_webuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser
    ADD CONSTRAINT user_auth_webuser_email_key UNIQUE (email);


--
-- Name: user_auth_webuser_groups user_auth_webuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_groups
    ADD CONSTRAINT user_auth_webuser_groups_pkey PRIMARY KEY (id);


--
-- Name: user_auth_webuser_groups user_auth_webuser_groups_webuser_id_group_id_411bcee0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_groups
    ADD CONSTRAINT user_auth_webuser_groups_webuser_id_group_id_411bcee0_uniq UNIQUE (webuser_id, group_id);


--
-- Name: user_auth_webuser user_auth_webuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser
    ADD CONSTRAINT user_auth_webuser_pkey PRIMARY KEY (id);


--
-- Name: user_auth_webuser_user_permissions user_auth_webuser_user_p_webuser_id_permission_id_ca164b65_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_user_permissions
    ADD CONSTRAINT user_auth_webuser_user_p_webuser_id_permission_id_ca164b65_uniq UNIQUE (webuser_id, permission_id);


--
-- Name: user_auth_webuser_user_permissions user_auth_webuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_user_permissions
    ADD CONSTRAINT user_auth_webuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_auth_webuser user_auth_webuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser
    ADD CONSTRAINT user_auth_webuser_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: otp_static_staticdevice_user_id_7f9cff2b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX otp_static_staticdevice_user_id_7f9cff2b ON public.otp_static_staticdevice USING btree (user_id);


--
-- Name: otp_static_statictoken_device_id_74b7c7d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX otp_static_statictoken_device_id_74b7c7d1 ON public.otp_static_statictoken USING btree (device_id);


--
-- Name: otp_static_statictoken_token_d0a51866; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX otp_static_statictoken_token_d0a51866 ON public.otp_static_statictoken USING btree (token);


--
-- Name: otp_static_statictoken_token_d0a51866_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX otp_static_statictoken_token_d0a51866_like ON public.otp_static_statictoken USING btree (token varchar_pattern_ops);


--
-- Name: otp_totp_totpdevice_user_id_0fb18292; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX otp_totp_totpdevice_user_id_0fb18292 ON public.otp_totp_totpdevice USING btree (user_id);


--
-- Name: pong_match_player_id_528a831b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pong_match_player_id_528a831b ON public.pong_match USING btree (player_id);


--
-- Name: tournament_match_loser_id_a8a9d8ca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_match_loser_id_a8a9d8ca ON public.tournament_match USING btree (loser_id);


--
-- Name: tournament_match_participant_one_id_d45451a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_match_participant_one_id_d45451a2 ON public.tournament_match USING btree (participant_one_id);


--
-- Name: tournament_match_participant_two_id_b93e5808; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_match_participant_two_id_b93e5808 ON public.tournament_match USING btree (participant_two_id);


--
-- Name: tournament_match_tournament_id_8996007e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_match_tournament_id_8996007e ON public.tournament_match USING btree (tournament_id);


--
-- Name: tournament_match_winner_id_1c48e34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_match_winner_id_1c48e34d ON public.tournament_match USING btree (winner_id);


--
-- Name: tournament_participant_tournament_id_b5dbeea2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_participant_tournament_id_b5dbeea2 ON public.tournament_participant USING btree (tournament_id);


--
-- Name: tournament_participant_user_id_ecbb967d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_participant_user_id_ecbb967d ON public.tournament_participant USING btree (user_id);


--
-- Name: tournament_tournament_creator_id_18d373f3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_tournament_creator_id_18d373f3 ON public.tournament_tournament USING btree (creator_id);


--
-- Name: tournament_tournament_winner_id_a7be84b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tournament_tournament_winner_id_a7be84b4 ON public.tournament_tournament USING btree (winner_id);


--
-- Name: user_auth_custompermission_custompermissionsmixin_id_ac0eb522; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_custompermission_custompermissionsmixin_id_ac0eb522 ON public.user_auth_custompermissionsmixin_groups USING btree (custompermissionsmixin_id);


--
-- Name: user_auth_custompermission_custompermissionsmixin_id_cec37522; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_custompermission_custompermissionsmixin_id_cec37522 ON public.user_auth_custompermissionsmixin_user_permissions USING btree (custompermissionsmixin_id);


--
-- Name: user_auth_custompermission_permission_id_777f7340; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_custompermission_permission_id_777f7340 ON public.user_auth_custompermissionsmixin_user_permissions USING btree (permission_id);


--
-- Name: user_auth_custompermissionsmixin_groups_group_id_df8508a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_custompermissionsmixin_groups_group_id_df8508a3 ON public.user_auth_custompermissionsmixin_groups USING btree (group_id);


--
-- Name: user_auth_userotp_user_id_8069940a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_userotp_user_id_8069940a ON public.user_auth_userotp USING btree (user_id);


--
-- Name: user_auth_webuser_email_5cb86fa9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_email_5cb86fa9_like ON public.user_auth_webuser USING btree (email varchar_pattern_ops);


--
-- Name: user_auth_webuser_groups_group_id_55727878; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_groups_group_id_55727878 ON public.user_auth_webuser_groups USING btree (group_id);


--
-- Name: user_auth_webuser_groups_webuser_id_ad2dfd90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_groups_webuser_id_ad2dfd90 ON public.user_auth_webuser_groups USING btree (webuser_id);


--
-- Name: user_auth_webuser_user_permissions_permission_id_e6f1d052; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_user_permissions_permission_id_e6f1d052 ON public.user_auth_webuser_user_permissions USING btree (permission_id);


--
-- Name: user_auth_webuser_user_permissions_webuser_id_895b7a51; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_user_permissions_webuser_id_895b7a51 ON public.user_auth_webuser_user_permissions USING btree (webuser_id);


--
-- Name: user_auth_webuser_username_037c54c4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_auth_webuser_username_037c54c4_like ON public.user_auth_webuser USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_auth_webuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_auth_webuser_id FOREIGN KEY (user_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_static_staticdevice otp_static_staticdev_user_id_7f9cff2b_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_static_staticdevice
    ADD CONSTRAINT otp_static_staticdev_user_id_7f9cff2b_fk_user_auth FOREIGN KEY (user_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_static_statictoken otp_static_statictok_device_id_74b7c7d1_fk_otp_stati; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_static_statictoken
    ADD CONSTRAINT otp_static_statictok_device_id_74b7c7d1_fk_otp_stati FOREIGN KEY (device_id) REFERENCES public.otp_static_staticdevice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_totp_totpdevice otp_totp_totpdevice_user_id_0fb18292_fk_user_auth_webuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_totp_totpdevice
    ADD CONSTRAINT otp_totp_totpdevice_user_id_0fb18292_fk_user_auth_webuser_id FOREIGN KEY (user_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pong_match pong_match_player_id_528a831b_fk_user_auth_webuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pong_match
    ADD CONSTRAINT pong_match_player_id_528a831b_fk_user_auth_webuser_id FOREIGN KEY (player_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_match tournament_match_loser_id_a8a9d8ca_fk_tournament_participant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_loser_id_a8a9d8ca_fk_tournament_participant_id FOREIGN KEY (loser_id) REFERENCES public.tournament_participant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_match tournament_match_participant_one_id_d45451a2_fk_tournamen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_participant_one_id_d45451a2_fk_tournamen FOREIGN KEY (participant_one_id) REFERENCES public.tournament_participant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_match tournament_match_participant_two_id_b93e5808_fk_tournamen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_participant_two_id_b93e5808_fk_tournamen FOREIGN KEY (participant_two_id) REFERENCES public.tournament_participant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_match tournament_match_tournament_id_8996007e_fk_tournamen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_tournament_id_8996007e_fk_tournamen FOREIGN KEY (tournament_id) REFERENCES public.tournament_tournament(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_match tournament_match_winner_id_1c48e34d_fk_tournamen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_match
    ADD CONSTRAINT tournament_match_winner_id_1c48e34d_fk_tournamen FOREIGN KEY (winner_id) REFERENCES public.tournament_participant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_participant tournament_participa_tournament_id_b5dbeea2_fk_tournamen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_participant
    ADD CONSTRAINT tournament_participa_tournament_id_b5dbeea2_fk_tournamen FOREIGN KEY (tournament_id) REFERENCES public.tournament_tournament(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_participant tournament_participant_user_id_ecbb967d_fk_user_auth_webuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_participant
    ADD CONSTRAINT tournament_participant_user_id_ecbb967d_fk_user_auth_webuser_id FOREIGN KEY (user_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_tournament tournament_tournamen_creator_id_18d373f3_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_tournament
    ADD CONSTRAINT tournament_tournamen_creator_id_18d373f3_fk_user_auth FOREIGN KEY (creator_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tournament_tournament tournament_tournamen_winner_id_a7be84b4_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tournament_tournament
    ADD CONSTRAINT tournament_tournamen_winner_id_a7be84b4_fk_user_auth FOREIGN KEY (winner_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_custompermissionsmixin_groups user_auth_customperm_custompermissionsmix_ac0eb522_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_groups
    ADD CONSTRAINT user_auth_customperm_custompermissionsmix_ac0eb522_fk_user_auth FOREIGN KEY (custompermissionsmixin_id) REFERENCES public.user_auth_custompermissionsmixin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_custompermissionsmixin_user_permissions user_auth_customperm_custompermissionsmix_cec37522_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_user_permissions
    ADD CONSTRAINT user_auth_customperm_custompermissionsmix_cec37522_fk_user_auth FOREIGN KEY (custompermissionsmixin_id) REFERENCES public.user_auth_custompermissionsmixin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_custompermissionsmixin_groups user_auth_customperm_group_id_df8508a3_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_groups
    ADD CONSTRAINT user_auth_customperm_group_id_df8508a3_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_custompermissionsmixin_user_permissions user_auth_customperm_permission_id_777f7340_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_custompermissionsmixin_user_permissions
    ADD CONSTRAINT user_auth_customperm_permission_id_777f7340_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_userotp user_auth_userotp_user_id_8069940a_fk_user_auth_webuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_userotp
    ADD CONSTRAINT user_auth_userotp_user_id_8069940a_fk_user_auth_webuser_id FOREIGN KEY (user_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_webuser_groups user_auth_webuser_gr_webuser_id_ad2dfd90_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_groups
    ADD CONSTRAINT user_auth_webuser_gr_webuser_id_ad2dfd90_fk_user_auth FOREIGN KEY (webuser_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_webuser_groups user_auth_webuser_groups_group_id_55727878_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_groups
    ADD CONSTRAINT user_auth_webuser_groups_group_id_55727878_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_webuser_user_permissions user_auth_webuser_us_permission_id_e6f1d052_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_user_permissions
    ADD CONSTRAINT user_auth_webuser_us_permission_id_e6f1d052_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_auth_webuser_user_permissions user_auth_webuser_us_webuser_id_895b7a51_fk_user_auth; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_auth_webuser_user_permissions
    ADD CONSTRAINT user_auth_webuser_us_webuser_id_895b7a51_fk_user_auth FOREIGN KEY (webuser_id) REFERENCES public.user_auth_webuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

