# Generated by Django 4.2.1 on 2024-03-14 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_player1', models.CharField(max_length=20)),
                ('guest_player2', models.CharField(blank=True, max_length=20, null=True)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('score_player', models.IntegerField(default=0)),
                ('score_guest_player1', models.IntegerField(default=0)),
                ('score_guest_player2', models.IntegerField(blank=True, default=0, null=True)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
